# Generated by Django 4.2.7 on 2023-11-12 13:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_alter_donor_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationprocess',
            name='finished_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
