# Generated by Django 4.2.7 on 2023-11-29 19:21

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ("donation", "0003_alter_donationprocess_finished_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donor",
            name="city",
        ),
        migrations.RemoveField(
            model_name="donor",
            name="health_condition",
        ),
        migrations.RemoveField(
            model_name="donor",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="donor",
            name="zip_code",
        ),
        migrations.RemoveField(
            model_name="hospital",
            name="city",
        ),
        migrations.RemoveField(
            model_name="hospital",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="hospital",
            name="zip_code",
        ),
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(default="Zabrze", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=phone_field.models.PhoneField(
                default=123456789, max_length=31, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="zip_code",
            field=models.CharField(default=-759, max_length=20),
            preserve_default=False,
        ),
    ]
