# Generated by Django 4.2.7 on 2023-12-08 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("donation", "0004_remove_donor_city_remove_donor_health_condition_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DonationResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "donation_type",
                    models.CharField(
                        choices=[("blood", "Blood"), ("marrow", "Marrow")],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="donor",
            name="user",
        ),
        migrations.RemoveField(
            model_name="donordiseases",
            name="donor",
        ),
        migrations.RemoveField(
            model_name="hospital",
            name="user",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="hospital",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_donor",
        ),
        migrations.AddField(
            model_name="user",
            name="hospital_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="website_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="donation",
            name="donor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.DeleteModel(
            name="DonationProcess",
        ),
        migrations.DeleteModel(
            name="Donor",
        ),
        migrations.DeleteModel(
            name="DonorDiseases",
        ),
        migrations.DeleteModel(
            name="Hospital",
        ),
        migrations.DeleteModel(
            name="Patient",
        ),
        migrations.AddField(
            model_name="donationresponse",
            name="donation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="donation.donation"
            ),
        ),
        migrations.AddField(
            model_name="donationresponse",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="donation.question"
            ),
        ),
        migrations.AddField(
            model_name="donation",
            name="questions",
            field=models.ManyToManyField(
                through="donation.DonationResponse", to="donation.question"
            ),
        ),
    ]
