# Generated by Django 4.2.7 on 2023-12-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0005_donationresponse_question_remove_donor_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='organ',
        ),
        migrations.AddField(
            model_name='donation',
            name='donation_type',
            field=models.CharField(choices=[('blood', 'Blood'), ('marrow', 'Marrow')], default='', max_length=10),
            preserve_default=False,
        ),
    ]
