# Generated by Django 4.2.7 on 2023-12-08 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0009_alter_question_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('can_view_user', 'Can view user'),)},
        ),
    ]
