# Generated by Django 4.2.7 on 2023-12-09 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("donation", "0011_alter_user_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"permissions": (("view_all_users", "Can view users"),)},
        ),
    ]
