# Generated by Django 4.2.7 on 2023-12-09 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("donation", "0012_alter_user_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
    ]
