# Generated by Django 4.2.7 on 2023-12-09 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donation", "0016_alter_user_hospital_name_alter_user_is_hospital"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_hospital",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
