# Generated by Django 5.0 on 2023-12-24 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("donation", "0019_user_new_questions_available"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="new_questions_available",
        ),
    ]
