# Generated by Django 5.0 on 2023-12-25 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0020_remove_user_new_questions_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='donation',
            name='donation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation.donationtype'),
        ),
        migrations.AlterField(
            model_name='question',
            name='donation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation.donationtype'),
        ),
    ]
