export const DONATION_LIST_REQUEST = "DONATION_LIST_REQUEST";
export const DONATION_LIST_SUCCESS = "DONATION_LIST_SUCCESS";
export const DONATION_LIST_FAIL = "DONATION_LIST_FAIL";

export const DONATION_DETAILS_REQUEST = "DONATION_DETAILS_REQUEST";
export const DONATION_DETAILS_SUCCESS = "DONATION_DETAILS_SUCCESS";
export const DONATION_DETAILS_FAIL = "DONATION_DETAILS_FAIL";

export const DONATION_LIST_MY_REQUEST = "DONATION_LIST_MY_REQUEST";
export const DONATION_LIST_MY_SUCCESS = "DONATION_LIST_MY_SUCCESS";
export const DONATION_LIST_MY_FAIL = "DONATION_LIST_MY_FAIL";
export const DONATION_LIST_MY_RESET = "DONATION_LIST_MY_RESET";

export const DONATION_CREATE_REQUEST = "DONATION_CREATE_REQUEST";
export const DONATION_CREATE_SUCCESS = "DONATION_CREATE_SUCCESS";
export const DONATION_CREATE_FAIL = "DONATION_CREATE_FAIL";

export const DONATION_DELETE_REQUEST = "DONATION_DELETE_REQUEST";
export const DONATION_DELETE_SUCCESS = "DONATION_DELETE_SUCCESS";
export const DONATION_DELETE_FAIL = "DONATION_DELETE_FAIL";


export const QUESTION_REQUEST = "QUESTION_REQUEST";
export const QUESTION_SUCCESS = "QUESTION_SUCCESS";
export const QUESTION_FAIL = "QUESTION_FAIL";

export const RESPONSE_LIST_REQUEST = "RESPONSE_LIST_REQUEST";
export const RESPONSE_LIST_SUCCESS = "RESPONSE_LIST_SUCCESS";
export const RESPONSE_LIST_FAIL = "RESPONSE_LIST_FAIL";

export const RESPONSE_CREATE_REQUEST = "RESPONSE_CREATE_REQUEST";
export const RESPONSE_CREATE_SUCCESS = "RESPONSE_CREATE_SUCCESS";
export const RESPONSE_CREATE_FAIL = "RESPONSE_CREATE_FAIL";






